/* tslint:disable */
/* eslint-disable */
/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderByDirection = {
    Default: 'DEFAULT',
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type OrderByDirection = typeof OrderByDirection[keyof typeof OrderByDirection];


export function OrderByDirectionFromJSON(json: any): OrderByDirection {
    return OrderByDirectionFromJSONTyped(json, false);
}

export function OrderByDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderByDirection {
    return json as OrderByDirection;
}

export function OrderByDirectionToJSON(value?: OrderByDirection | null): any {
    return value as any;
}

