/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderByDirection = {
    Default: 'DEFAULT',
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type OrderByDirection = typeof OrderByDirection[keyof typeof OrderByDirection];


export function OrderByDirectionFromJSON(json: any): OrderByDirection {
    return OrderByDirectionFromJSONTyped(json, false);
}

export function OrderByDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderByDirection {
    return json as OrderByDirection;
}

export function OrderByDirectionToJSON(value?: OrderByDirection | null): any {
    return value as any;
}

