/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistCreateProductListRequest
 */
export interface ProductlistCreateProductListRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListRequest
     */
    'code'?: string;
    /**
     * 
     * @type {ProductlistLocalizedText}
     * @memberof ProductlistCreateProductListRequest
     */
    'urlKey'?: ProductlistLocalizedText;
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListRequest
     */
    'entityType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListRequest
     */
    'entityCode'?: string;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductlistCreateProductListRequest
     */
    'attributes'?: { [key: string]: ProtobufAny; };
}
