/* tslint:disable */
/* eslint-disable */
/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistUpdateProductListRequest
 */
export interface ProductlistUpdateProductListRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductlistUpdateProductListRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistUpdateProductListRequest
     */
    'id'?: string;
    /**
     * 
     * @type {ProductlistLocalizedText}
     * @memberof ProductlistUpdateProductListRequest
     */
    'urlKey'?: ProductlistLocalizedText;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof ProductlistUpdateProductListRequest
     */
    'attributes'?: { [key: string]: ProtobufAny; };
    /**
     * 
     * @type {string}
     * @memberof ProductlistUpdateProductListRequest
     */
    'attributesMask'?: string;
}
