/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistProductListAssociationError
 */
export interface ProductlistProductListAssociationError {
    /**
     * 
     * @type {string}
     * @memberof ProductlistProductListAssociationError
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistProductListAssociationError
     */
    'message'?: string;
}
