/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistDeleteProductListAssociationResponse
 */
export interface ProductlistDeleteProductListAssociationResponse {
    /**
     * 
     * @type {ProductlistProductListAssociation}
     * @memberof ProductlistDeleteProductListAssociationResponse
     */
    'association'?: ProductlistProductListAssociation;
    /**
     * 
     * @type {Array<ProductlistProductListAssociationError>}
     * @memberof ProductlistDeleteProductListAssociationResponse
     */
    'errors'?: Array<ProductlistProductListAssociationError>;
}
