/* tslint:disable */
/* eslint-disable */
/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistDeleteProductListAssociationResponse
 */
export interface ProductlistDeleteProductListAssociationResponse {
    /**
     * 
     * @type {ProductlistProductListAssociation}
     * @memberof ProductlistDeleteProductListAssociationResponse
     */
    'association'?: ProductlistProductListAssociation;
    /**
     * 
     * @type {Array<ProductlistProductListAssociationError>}
     * @memberof ProductlistDeleteProductListAssociationResponse
     */
    'errors'?: Array<ProductlistProductListAssociationError>;
}
