/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistCreateProductListAssociationRequest
 */
export interface ProductlistCreateProductListAssociationRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListAssociationRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListAssociationRequest
     */
    'listId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductlistCreateProductListAssociationRequest
     */
    'position'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductlistCreateProductListAssociationRequest
     */
    'productGrn'?: string;
}
