/* tslint:disable */
/* eslint-disable */
/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistListProductListAssociationsResponse
 */
export interface ProductlistListProductListAssociationsResponse {
    /**
     * 
     * @type {Array<ProductlistProductListAssociation>}
     * @memberof ProductlistListProductListAssociationsResponse
     */
    'associations'?: Array<ProductlistProductListAssociation>;
    /**
     * 
     * @type {string}
     * @memberof ProductlistListProductListAssociationsResponse
     */
    'nextPageToken'?: string;
}
