/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistGetProductListByIdRequest
 */
export interface ProductlistGetProductListByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductlistGetProductListByIdRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductlistGetProductListByIdRequest
     */
    'id'?: string;
}
