/* tslint:disable */
/* eslint-disable */
/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ProductlistSearchProductListsByIdsRequest
 */
export interface ProductlistSearchProductListsByIdsRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductlistSearchProductListsByIdsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductlistSearchProductListsByIdsRequest
     */
    'ids'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ProductlistSearchProductListsByIdsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductlistSearchProductListsByIdsRequest
     */
    'pageNumber'?: number;
}
