/* tslint:disable */
/* eslint-disable */
/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface SetProductListAssociationsRequestAssociation
 */
export interface SetProductListAssociationsRequestAssociation {
    /**
     * 
     * @type {string}
     * @memberof SetProductListAssociationsRequestAssociation
     */
    'listId'?: string;
    /**
     * 
     * @type {number}
     * @memberof SetProductListAssociationsRequestAssociation
     */
    'position'?: number;
    /**
     * 
     * @type {string}
     * @memberof SetProductListAssociationsRequestAssociation
     */
    'productGrn'?: string;
}
