/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistProductListAssociation } from '../models/ProductlistProductListAssociation';
import { ProductlistProductListAssociationError } from '../models/ProductlistProductListAssociationError';
import { HttpFile } from '../http/http';

export class ProductlistCreateProductListAssociationResponse {
    'association'?: ProductlistProductListAssociation;
    'errors'?: Array<ProductlistProductListAssociationError>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "association",
            "baseName": "association",
            "type": "ProductlistProductListAssociation",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ProductlistProductListAssociationError>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistCreateProductListAssociationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

