/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistOrderBy } from '../models/ProductlistOrderBy';
import { HttpFile } from '../http/http';

export class ProductlistListProductListAssociationsRequest {
    'tenantId'?: string;
    'listId'?: string;
    'productGrn'?: string;
    'pageSize'?: number;
    'pageToken'?: string;
    'orderBy'?: Array<ProductlistOrderBy>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "listId",
            "baseName": "listId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productGrn",
            "baseName": "productGrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderBy",
            "baseName": "orderBy",
            "type": "Array<ProductlistOrderBy>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistListProductListAssociationsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

