/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistProductListEntity } from '../models/ProductlistProductListEntity';
import { HttpFile } from '../http/http';

export class ProductlistSearchProductListsResponse {
    'results'?: Array<ProductlistProductListEntity>;
    'totalSize'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ProductlistProductListEntity>",
            "format": ""
        },
        {
            "name": "totalSize",
            "baseName": "totalSize",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ProductlistSearchProductListsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

