/**
 * Collection Service
 * API for managing collection
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistProductListEntity } from '../models/ProductlistProductListEntity';
import { HttpFile } from '../http/http';

export class ProductlistSearchProductListsByIdsResponse {
    'results'?: Array<ProductlistProductListEntity>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<ProductlistProductListEntity>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistSearchProductListsByIdsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

