/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchProductListsRequestQuery } from '../models/SearchProductListsRequestQuery';
import { HttpFile } from '../http/http';

export class ProductlistSearchProductListsRequest {
    'tenantId'?: string;
    'query'?: SearchProductListsRequestQuery;
    'pageSize'?: number;
    'pageNumber'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "SearchProductListsRequestQuery",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ProductlistSearchProductListsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

