/**
 * Collection Service
 * API for managing collection
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderByDirection } from '../models/OrderByDirection';
import { HttpFile } from '../http/http';

export class ProductlistOrderBy {
    'field'?: string;
    'direction'?: OrderByDirection;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "OrderByDirection",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistOrderBy.attributeTypeMap;
    }

    public constructor() {
    }
}



