/**
 * product-list/bulk_update_product_list_associations.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistProductListAssociation } from '../models/ProductlistProductListAssociation';
import { HttpFile } from '../http/http';

export class ProductlistGetProductListAssociationsByProductGrnResponse {
    'associations'?: Array<ProductlistProductListAssociation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "associations",
            "baseName": "associations",
            "type": "Array<ProductlistProductListAssociation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistGetProductListAssociationsByProductGrnResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

