/**
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductlistProductListEntity } from '../models/ProductlistProductListEntity';
import { HttpFile } from '../http/http';

export class ProductlistListProductListsResponse {
    'lists'?: Array<ProductlistProductListEntity>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lists",
            "baseName": "lists",
            "type": "Array<ProductlistProductListEntity>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductlistListProductListsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

